version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: hanamura-mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ernestochero
      MONGO_INITDB_ROOT_PASSWORD: 1234#1234
      MONGO_INITDB_DATABASE: hanamuradb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro